name: Drone Server
description: |
  Drone server (version 0.5) runs the UI and API
version: # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: Artur Grabowski
license: Do whatever you want with it license
projectURL: https://github.com/majest/rancher-catalog
