.catalog:
  name: Drone Server 0.5
  version: 0.2
  description: |
    Drone CI Server (version  0.5)
  questions:
    - variable: "DRONE_SECRET"
      type: "string"
      label: "Drone secret"
      description: "Randomly generated string that will be used as a secret"
    - variable: "CONSUMER_KEY"
      type: "string"
      label: "Key"
      description: "Consumer key that is usually obtained from Github/Bitbucket pauth configuration"
    - variable: "CONSUMER_SECRET"
      type: "string"
      label: "Secret"
      description: "Consumer secret that is usually obtained from Github/Bitbucket pauth configuration"
    - variable: "REPO_USER"
      type: "string"
      label: "User"
      description: "Repository username that will be used as a drone admin"
    - variable: "LB_PORT"
      type: "int"
      required: true
      label: "Public Port"
      description: "Port that the load balancer will listen on. Must be accessible to remote driver for webhooks"
    - variable: "DB_DRIVER"
      type: "enum"
      label: "Database Driver"
      description: "Database backend to use."
      required: true
      default: "sqlite3"
      options:
        - sqlite3
        - postgres
        - mysql
    - variable: "DB_CONFIG"
      label: "Database Config"
      type: "string"
      required: true
      default: /var/lib/drone/drone.sqlite
      description: "Must be full db string. The hostname for the DB will be 'database'. See http://readme.drone.io/setup/overview/ for more info"

    - variable: "DRONE_SERVER"
      type: "service"
      label: "Drone Server Load Balancer"
      description: "Drone server load balancer to link to."
      default: "drone-lb"
    - variable: DRONE_DEBUG
      label: Debug mode
      description: |
        Runs the agent in debug mode. This will result in more logging being
        produced by the agent.
      required: true
      type: boolean
      default: false
    - variable: DRONE_BACKOFF
      label: Backoff time
      description: |
        The backoff time to reconnect agents when their connection to the
        central server is interrupted.
      required: false
      type: string
      default: "10"
    - variable: DRONE_PLUGIN_PULL
      label: Update plugins automatically
      description: |
        Whether plugins are pulled automatically by the agent.
      type: boolean
      default: true
    - variable: DRONE_PLUGIN_NAMESPACE
      label: Plugin namespace in DockerHub
      description: Plugin namespace in DockerHub.
      default: plugins
      type: string
    - variable: DRONE_PLUGIN_WHITELIST
      label: Plugin whitelist
      description: |
        Plugin whitelist. Add to the string to include additional locations of
        plugins.
      type: string
      default: "plugins/*"
    - variable: DOCKER_HOST
      label: Docker host address
      description: Docker host address
      type: string
      default: "unix:///var/run/docker.sock"
    - variable: DOCKER_TLS_VERIFY
      label: Docker requires TLS verification (optional).
      description: |
        Whether Docker requires TLS verification.
      type: boolean
      default: false
    - variable: DOCKER_CERT_PATH
      label: Docker certificate path (optional).
      description: Docker certificate path.
      type: string
      default: ""
    - variable: DOCKER_MAX_PROCS
      label: Docker concurrent build processes.
      description: |
        The number of concurrent builds run by the agent.
      type: int
      default: 1
    - variable: DOCKER_OS
      label: Docker operating system
      description: |
        The operating system in use.
      type: enum
      options:
        - linux
        - android
        - freebsd
        - solaris
        - windows
      default: linux
    - variable: DOCKER_ARCH
      label: Docker architecture
      description: |
        The CPU architecture of the host.
      type: enum
      options:
        - amd64
        - arm
        - arm64
      default: amd64
    - variable: HTTP_PROXY
      label: The proxy for HTTP connections (optional).
      description: |
        The proxy for HTTP connections. Used when Drone is running behind a
        firewall.
      required: false
      type: string
    - variable: HTTPS_PROXY
      label: The proxy for HTTPS connections (optional).
      description: |
        The proxy for HTTPS connections. Used when Drone is running behind a
        firewall.
      required: false
      type: string
    - variable: NO_PROXY
      label: The sites to not proxy (optional).
      description: |
        The sites to not proxy. Used when Drone is running behind a
        firewall.
      required: false
      type: string
drone-lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
drone-server:
  scale: 1
  metadata:
    drone_secret: ${DRONE_SECRET}
    consumer_secret: ${CONSUMER_SECRET}
    consumer_key: ${CONSUMER_KEY}
    repo_user: ${REPO_USER}
    database_driver: ${DB_DRIVER}
    database_config: "${DB_CONFIG}"
    debug: "true"
  health_check:
    port: 1620
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET /ping HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
